# SPDX-FileCopyrightText: 2026 DennyWanye
# SPDX-License-Identifier: Apache-2.0

"""Public Tool, authorization, and reconciliation contracts."""

from .authorization import (
    AuthorizationDecision,
    AuthorizationPort,
    AuthorizationReceipt,
    AuthorizationRequest,
    AuthorizationResult,
    PreparedToolEffect,
    bind_authorization_receipts,
    sdk_authorization_receipt,
)
from .contracts import (
    CancellationToken,
    FunctionTool,
    JsonObject,
    Tool,
    ToolCall,
    ToolContext,
    ToolHandler,
    ToolOutcome,
    ToolResult,
    ToolSpec,
)
from .errors import (
    DuplicateToolCallError,
    DuplicateToolError,
    LateToolResultError,
    MalformedToolArgumentsError,
    ToolRegistryError,
    UnknownToolError,
)
from .executor import EffectExecution, EffectExecutor, ToolAuthorizationPending
from .reconciliation import (
    ReconciliationObservation,
    ReconciliationState,
    ToolReconciliationPort,
)
from .registry import ToolCallState, ToolRegistry
from .schema import ArgumentsValidationError, SchemaDefinitionError
from .sidecar import (
    EffectKind,
    EffectPolicy,
    FunctionOutcomeParser,
    OutcomeParserPort,
    ResourceScopeResolverPort,
    Sidecar,
    ToolCompletionSemantics,
    ToolDispatchKind,
    ToolInventoryRecord,
    ToolOutcomeParser,
    ToolResource,
    ToolSidecar,
    builtin_outcome_parser,
    inventory_digest,
    parse_tool_outcome,
    resource_digest,
)


__all__ = (
    "ArgumentsValidationError",
    "AuthorizationDecision",
    "AuthorizationPort",
    "AuthorizationReceipt",
    "AuthorizationRequest",
    "AuthorizationResult",
    "CancellationToken",
    "DuplicateToolCallError",
    "DuplicateToolError",
    "EffectExecution",
    "EffectKind",
    "EffectPolicy",
    "FunctionOutcomeParser",
    "EffectExecutor",
    "FunctionTool",
    "JsonObject",
    "LateToolResultError",
    "MalformedToolArgumentsError",
    "OutcomeParserPort",
    "PreparedToolEffect",
    "ReconciliationObservation",
    "ReconciliationState",
    "ResourceScopeResolverPort",
    "SchemaDefinitionError",
    "Sidecar",
    "Tool",
    "ToolCall",
    "ToolCallState",
    "ToolAuthorizationPending",
    "ToolContext",
    "ToolCompletionSemantics",
    "ToolDispatchKind",
    "ToolHandler",
    "ToolOutcome",
    "ToolOutcomeParser",
    "ToolResource",
    "ToolInventoryRecord",
    "ToolReconciliationPort",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolResult",
    "ToolSpec",
    "ToolSidecar",
    "UnknownToolError",
    "bind_authorization_receipts",
    "builtin_outcome_parser",
    "sdk_authorization_receipt",
    "inventory_digest",
    "parse_tool_outcome",
    "resource_digest",
)
