# SPDX-FileCopyrightText: 2026 DennyWanye
# SPDX-License-Identifier: Apache-2.0

"""Durable runtime lifecycle public surface, resolved without eager cycles."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_MODULE_EXPORTS = {
    "simple_harness.execution.context_authority": (
        "ContextRouteReceipt",
        "ContextRouteState",
        "RunContextAuthorityPort",
        "RunContextAuthorityRequest",
        "RunContextSnapshot",
        "RuntimeDecisionSinkPort",
        "TaskExecutionAuthorityPort",
        "TaskExecutionEnvelopeRequest",
    ),
    "simple_harness.execution.effects": ("TaskExecutionEnvelope",),
    "simple_harness.tools.runtime_catalog": (
        "ToolEffectClass",
        "ToolExecutionPolicy",
        "ToolRouteRequirement",
        "ToolTaskScopeRequirement",
    ),
    ".admission": ("AdmissionPort", "AdmissionVerdict", "AllowAllAdmission"),
    ".agent_memory": (
        "AgentIdentity",
        "AgentMemoryError",
        "AgentMemoryErrorCode",
        "AgentMemoryPort",
        "CommittedTurn",
        "CommittedTurnReceipt",
        "CommittedTurnStatus",
        "MemoryFailurePolicy",
        "MemoryRecallBounds",
        "MemoryRecallRequest",
        "MemoryRecallResult",
        "MemoryRecallStatus",
        "MemoryReleaseRequest",
        "MemoryScopeKind",
        "MemoryScopeRef",
        "ResourceOwnership",
    ),
    ".disclosure_protocol": (
        "HUMAN_MEMORY_SCHEMA_VERSION",
        "DeliveryRecipient",
        "DisclosureContext",
        "DisclosureGeneration",
        "DisclosurePurpose",
        "DisclosureReasonCode",
        "DisclosureSource",
        "DisclosureTrust",
        "IntendedAudience",
    ),
    ".evidence_protocol": (
        "AnalysisBudget",
        "AnalysisValidationStatus",
        "EvidenceReasonCode",
        "EvidenceRef",
        "EvidenceSourceKind",
        "ExecutionEvidence",
        "ExecutionEvidenceKind",
        "MemoryAnalysisDeliveryAuthorityPort",
        "MemoryAnalysisDeliveryReceipt",
        "MemoryAnalysisExecutorPort",
        "MemoryAnalysisReceipt",
        "MemoryAnalysisRequest",
        "MemoryAnalysisResult",
        "MemoryAnalysisResultEnvelope",
        "RemovedSpanSummary",
        "RemovedSpanType",
        "SanitizedEvidenceEnvelope",
        "SanitizedEvidenceReceipt",
    ),
    ".memory_protocol": (
        "ContextAssemblyBudget",
        "ContextAssemblyDecision",
        "ContextAssemblyReasonCode",
        "ContextFragment",
        "ContextFragmentType",
        "LongTermMemoryType",
        "MemoryMutationKind",
        "MemoryMutationOperation",
        "MemoryMutationPlan",
        "RecallBudget",
        "RecallContext",
        "RecallDecision",
        "RecallDecisionOutcome",
        "RecallPlan",
        "RecallReasonCode",
        "WorkingMemoryRole",
    ),
    ".task_scope_protocol": (
        "TaskScopeCandidate",
        "TaskScopeMutationKind",
        "TaskScopeMutationOperation",
        "TaskScopeMutationOutcome",
        "TaskScopeMutationPlan",
        "TaskScopeOpenReceipt",
        "TaskScopeOpenRequest",
        "TaskScopeProposal",
        "TaskScopeReasonCode",
        "TaskScopeRoute",
        "TaskScopeSearchReceipt",
        "TaskScopeSearchRequest",
    ),
    ".workspace_binding_protocol": (
        "WORKSPACE_BINDING_SCHEMA_VERSION",
        "CanonicalWorkspaceRoot",
        "FilesystemIdentity",
        "FilesystemIdentityKind",
        "HostIssuedRunBindingModeSnapshot",
        "ManualWorkspaceBindingAuthorizationReceipt",
        "ManualWorkspaceBindingChallenge",
        "RunBindingModeSnapshotRequest",
        "WorkspaceBindingAuthorizationChannel",
        "WorkspaceBindingAuthorizationDecision",
        "WorkspaceBindingAuthorityGrant",
        "WorkspaceBindingAuthorityPort",
        "WorkspaceBindingGrantSource",
        "WorkspaceBindingMode",
        "WorkspaceBindingProposal",
        "WorkspaceBindingSetReceipt",
    ),
    ".child_runs": (
        "ChildLaunchRequest",
        "ChildRunHandle",
        "ChildRunUnitOfWork",
        "ProfileLaunchTicketRef",
    ),
    ".child_signal_runtime": ("ChildSignalRuntime", "ChildSignalUnitOfWork"),
    ".consumer_adapter": (
        "ConsumerRuntimePolicies",
        "ConsumerRuntimePorts",
        "build_consumer_runtime",
    ),
    ".context": ("ContextPort", "ContextSnapshot", "SqliteContextPort"),
    ".conversation_context": (
        "claim_context_preparation",
        "complete_context_stage",
        "context_input_hash",
        "context_query_id",
        "get_staged_context",
    ),
    ".conversation_context_provider": (
        "ConversationContextBounds",
        "ConversationContextProviderPort",
        "ConversationContextRequest",
        "ConversationContextResult",
        "CurrentMessageContextProvider",
        "source_snapshot_ref",
    ),
    ".conversation_memory": (
        "ConversationContinuationInput",
        "ConversationTurnInput",
        "ConversationTurnOutput",
    ),
    ".commands": (
        "COMMAND_FRAME_MAX_BYTES",
        "COMMAND_MESSAGE_MAX_BYTES",
        "CancelCommandIntent",
        "CommandError",
        "CommandErrorCode",
        "CommandKind",
        "CommandOutputState",
        "CommandReceipt",
        "CommandRetryState",
        "CommandSnapshot",
        "CommandState",
        "ContinueCommandIntent",
        "RunApiMode",
        "StartCommandIntent",
    ),
    ".drivers.react": ("ReActDriver", "build_react_driver"),
    ".drivers.react_loop": ("AgentLoopCollaborator", "EffectBatchExecutor"),
    ".drivers.workflow": (
        "WORKFLOW_DRIVER_IMPLEMENTATION_FINGERPRINT",
        "WORKFLOW_DRIVER_KIND",
        "WorkflowRuntimeDriver",
        "build_workflow_runtime_driver",
    ),
    ".kernel": (
        "ROOT_PROFILE_KEY",
        "DriverCancellationCoordinator",
        "DriverCancellationRecovery",
        "DriverCancelOutcome",
        "DriverInvocation",
        "DriverResult",
        "RunClient",
        "Runtime",
        "RuntimeDriver",
        "RuntimeLifecycleState",
        "RuntimePorts",
        "RuntimeProfile",
        "RuntimeReconciliationPort",
        "RuntimeServices",
        "RuntimeUnitOfWork",
        "ToolCatalogGenerationPort",
        "build_runtime",
    ),
    ".ports": (
        "AuthorizationPort",
        "AuthorizationRequest",
        "AuthorizationResult",
        "ProviderPort",
        "ToolExecutorPort",
    ),
    ".production": ("ProductionRuntimeConfig", "build_production_runtime"),
    ".reconciler": (
        "STARTUP_RECONCILIATION_ORDER",
        "ReconciliationPhase",
        "StartupReconciler",
        "StartupReconciliationSteps",
    ),
    ".start_snapshot": (
        "HOST_CONTROL_INPUT_MAX_BYTES",
        "HostControlAuthorityV1",
        "HostControlRunStartV1",
        "RunStart",
        "StartSnapshot",
    ),
    ".terminal": ("TerminalCoordinator", "ToolCatalogStale"),
    ".user_continuations": ("ContinuationUnitOfWork", "UserContinuationRuntime"),
}

_EXPORT_TO_MODULE = {
    name: module_name for module_name, names in _MODULE_EXPORTS.items() for name in names
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORT_TO_MODULE))


__all__ = (
    "ROOT_PROFILE_KEY",
    "HOST_CONTROL_INPUT_MAX_BYTES",
    "HostControlAuthorityV1",
    "HostControlRunStartV1",
    "STARTUP_RECONCILIATION_ORDER",
    "WORKFLOW_DRIVER_IMPLEMENTATION_FINGERPRINT",
    "WORKFLOW_DRIVER_KIND",
    "AdmissionPort",
    "AdmissionVerdict",
    "AgentIdentity",
    "AgentMemoryError",
    "AgentMemoryErrorCode",
    "AgentMemoryPort",
    "AgentLoopCollaborator",
    "AnalysisBudget",
    "AnalysisValidationStatus",
    "AllowAllAdmission",
    "AuthorizationPort",
    "AuthorizationRequest",
    "AuthorizationResult",
    "ChildLaunchRequest",
    "ChildRunHandle",
    "ChildRunUnitOfWork",
    "ChildSignalRuntime",
    "ChildSignalUnitOfWork",
    "ConsumerRuntimePorts",
    "ConsumerRuntimePolicies",
    "CommittedTurn",
    "CommittedTurnReceipt",
    "CommittedTurnStatus",
    "COMMAND_FRAME_MAX_BYTES",
    "COMMAND_MESSAGE_MAX_BYTES",
    "CancelCommandIntent",
    "CommandError",
    "CommandErrorCode",
    "CommandKind",
    "CommandOutputState",
    "CommandReceipt",
    "CommandRetryState",
    "CommandSnapshot",
    "CommandState",
    "ContinueCommandIntent",
    "ContextRouteReceipt",
    "ContextRouteState",
    "ContextPort",
    "ContextSnapshot",
    "ContextAssemblyBudget",
    "ContextAssemblyDecision",
    "ContextAssemblyReasonCode",
    "ContextFragment",
    "ContextFragmentType",
    "ContinuationUnitOfWork",
    "ConversationContinuationInput",
    "ConversationContextBounds",
    "ConversationContextProviderPort",
    "ConversationContextRequest",
    "ConversationContextResult",
    "ConversationTurnInput",
    "ConversationTurnOutput",
    "DriverCancelOutcome",
    "DriverCancellationCoordinator",
    "DriverCancellationRecovery",
    "DriverInvocation",
    "DriverResult",
    "DeliveryRecipient",
    "DisclosureContext",
    "DisclosureGeneration",
    "DisclosurePurpose",
    "DisclosureReasonCode",
    "DisclosureSource",
    "DisclosureTrust",
    "EffectBatchExecutor",
    "EvidenceReasonCode",
    "EvidenceRef",
    "EvidenceSourceKind",
    "ExecutionEvidence",
    "ExecutionEvidenceKind",
    "MemoryAnalysisDeliveryAuthorityPort",
    "MemoryAnalysisDeliveryReceipt",
    "HUMAN_MEMORY_SCHEMA_VERSION",
    "WORKSPACE_BINDING_SCHEMA_VERSION",
    "CanonicalWorkspaceRoot",
    "FilesystemIdentity",
    "FilesystemIdentityKind",
    "HostIssuedRunBindingModeSnapshot",
    "IntendedAudience",
    "LongTermMemoryType",
    "CurrentMessageContextProvider",
    "MemoryAnalysisExecutorPort",
    "MemoryAnalysisReceipt",
    "MemoryAnalysisRequest",
    "MemoryAnalysisResult",
    "MemoryAnalysisResultEnvelope",
    "MemoryFailurePolicy",
    "ManualWorkspaceBindingAuthorizationReceipt",
    "ManualWorkspaceBindingChallenge",
    "MemoryMutationKind",
    "MemoryMutationOperation",
    "MemoryMutationPlan",
    "MemoryRecallBounds",
    "MemoryRecallRequest",
    "MemoryRecallResult",
    "MemoryRecallStatus",
    "MemoryReleaseRequest",
    "MemoryScopeKind",
    "MemoryScopeRef",
    "ProfileLaunchTicketRef",
    "ProviderPort",
    "ProductionRuntimeConfig",
    "RecallBudget",
    "RecallContext",
    "RecallDecision",
    "RecallDecisionOutcome",
    "RecallPlan",
    "RecallReasonCode",
    "ReconciliationPhase",
    "ReActDriver",
    "ResourceOwnership",
    "RunApiMode",
    "RunContextAuthorityPort",
    "RunContextAuthorityRequest",
    "RunContextSnapshot",
    "RunBindingModeSnapshotRequest",
    "RunClient",
    "RunStart",
    "Runtime",
    "RuntimeLifecycleState",
    "RuntimeDriver",
    "RuntimePorts",
    "RuntimeProfile",
    "RuntimeReconciliationPort",
    "RuntimeServices",
    "RuntimeUnitOfWork",
    "SqliteContextPort",
    "RuntimeDecisionSinkPort",
    "SanitizedEvidenceEnvelope",
    "SanitizedEvidenceReceipt",
    "StartSnapshot",
    "StartCommandIntent",
    "StartupReconciler",
    "StartupReconciliationSteps",
    "TerminalCoordinator",
    "TaskScopeCandidate",
    "TaskScopeMutationKind",
    "TaskScopeMutationOperation",
    "TaskScopeMutationOutcome",
    "TaskScopeMutationPlan",
    "TaskScopeOpenReceipt",
    "TaskScopeOpenRequest",
    "TaskScopeProposal",
    "TaskScopeReasonCode",
    "TaskScopeRoute",
    "TaskScopeSearchReceipt",
    "TaskScopeSearchRequest",
    "TaskExecutionAuthorityPort",
    "TaskExecutionEnvelope",
    "TaskExecutionEnvelopeRequest",
    "ToolCatalogGenerationPort",
    "ToolEffectClass",
    "ToolExecutionPolicy",
    "ToolRouteRequirement",
    "ToolTaskScopeRequirement",
    "ToolCatalogStale",
    "ToolExecutorPort",
    "UserContinuationRuntime",
    "WorkflowRuntimeDriver",
    "WorkingMemoryRole",
    "WorkspaceBindingAuthorizationDecision",
    "WorkspaceBindingAuthorizationChannel",
    "WorkspaceBindingAuthorityGrant",
    "WorkspaceBindingAuthorityPort",
    "WorkspaceBindingGrantSource",
    "WorkspaceBindingMode",
    "WorkspaceBindingProposal",
    "WorkspaceBindingSetReceipt",
    "RemovedSpanSummary",
    "RemovedSpanType",
    "build_consumer_runtime",
    "build_production_runtime",
    "build_runtime",
    "build_react_driver",
    "build_workflow_runtime_driver",
    "claim_context_preparation",
    "complete_context_stage",
    "context_input_hash",
    "context_query_id",
    "get_staged_context",
    "source_snapshot_ref",
)
