# SPDX-FileCopyrightText: 2026 DennyWanye
# SPDX-License-Identifier: Apache-2.0

"""Public package surface for Simple Harness SDK."""

from .contracts import (
    CallId,
    ContractValidationError,
    CorrelationIds,
    EffectId,
    ErrorCode,
    EventEnvelope,
    EventId,
    EventKind,
    ExecutionSessionId,
    FrozenJsonValue,
    HarnessError,
    JsonPrimitive,
    JsonValue,
    Message,
    MessageRole,
    RequestId,
    RunId,
    canonical_json,
    fingerprint_json,
    freeze_json,
    thaw_json,
    validate_json_value,
)
from .runtime import (
    ROOT_PROFILE_KEY,
    AdmissionPort,
    AdmissionVerdict,
    AllowAllAdmission,
    ContextPort,
    ContextSnapshot,
    DriverInvocation,
    DriverResult,
    RunClient,
    Runtime,
    RuntimeDriver,
    RuntimePorts,
    RuntimeProfile,
    RuntimeServices,
    RuntimeUnitOfWork,
    SqliteContextPort,
    build_runtime,
)
from .version import __version__

__all__ = (
    "__version__",
    "JsonPrimitive",
    "JsonValue",
    "FrozenJsonValue",
    "validate_json_value",
    "canonical_json",
    "freeze_json",
    "thaw_json",
    "fingerprint_json",
    "ExecutionSessionId",
    "RunId",
    "RequestId",
    "CallId",
    "EffectId",
    "EventId",
    "CorrelationIds",
    "MessageRole",
    "Message",
    "EventKind",
    "EventEnvelope",
    "ErrorCode",
    "HarnessError",
    "ContractValidationError",
    "ROOT_PROFILE_KEY",
    "AdmissionPort",
    "AdmissionVerdict",
    "AllowAllAdmission",
    "ContextPort",
    "ContextSnapshot",
    "DriverInvocation",
    "DriverResult",
    "RunClient",
    "Runtime",
    "RuntimeDriver",
    "RuntimePorts",
    "RuntimeProfile",
    "RuntimeServices",
    "RuntimeUnitOfWork",
    "SqliteContextPort",
    "build_runtime",
)
